function Get-ShareSurferPortProtocolExportSchema {
    [ordered]@{
        'port_protocol_manifest.csv' = @(
            'AssessmentId',
            'GeneratedAt',
            'ExportVersion',
            'CollectorComputerName',
            'CollectorFqdn',
            'CollectorUser',
            'UserDomain',
            'IsWindows',
            'IsElevated',
            'OSDescription',
            'OSArchitecture',
            'PowerShellVersion',
            'PSEdition',
            'ActiveDirectoryModuleAvailable',
            'SmbShareModuleAvailable',
            'TargetCount',
            'CheckCount',
            'PassedCount',
            'WarningCount',
            'FailedCount',
            'SkippedCount',
            'PackageKind'
        )
        'port_protocol_targets.csv' = @(
            'AssessmentId',
            'TargetId',
            'Target',
            'TargetType',
            'ComputerName',
            'ShareName',
            'UNCPath',
            'CheckCount',
            'PassedCount',
            'WarningCount',
            'FailedCount',
            'SkippedCount',
            'TargetStatus',
            'SuggestedNextAction'
        )
        'port_protocol_checks.csv' = @(
            'AssessmentId',
            'CheckId',
            'TargetId',
            'Target',
            'TargetType',
            'ComputerName',
            'ShareName',
            'Protocol',
            'Transport',
            'Port',
            'Requirement',
            'Provider',
            'Purpose',
            'RequiredFor',
            'Status',
            'Severity',
            'LatencyMs',
            'RemoteAddress',
            'Message',
            'Detail'
        )
    }
}
