function Get-ShareSurferExportSchema {
    [ordered]@{
        'shares.csv' = @(
            'ShareId',
            'Source',
            'ComputerName',
            'ShareName',
            'UNCPath',
            'LocalPath',
            'Description',
            'PartialData',
            'PartialReason'
        )
        'items.csv' = @(
            'ItemId',
            'ShareId',
            'ItemType',
            'FullPath',
            'RelativePath',
            'Depth',
            'Owner',
            'InheritanceEnabled',
            'InheritanceBrokenAt'
        )
        'share_permissions.csv' = @(
            'ShareId',
            'Identity',
            'Rights',
            'AccessControlType',
            'Source'
        )
        'acl_entries.csv' = @(
            'ItemId',
            'ShareId',
            'FullPath',
            'Identity',
            'Rights',
            'AccessControlType',
            'IsInherited',
            'InheritanceFlags',
            'PropagationFlags',
            'Depth'
        )
        'identities.csv' = @(
            'Identity',
            'SamAccountName',
            'DisplayName',
            'ObjectClass',
            'EmployeeId',
            'EmployeeNumber',
            'UserPrincipalName',
            'Mail',
            'Department',
            'Title',
            'Company',
            'Office',
            'AccountEnabled',
            'Manager',
            'ManagerLevel1',
            'ManagerLevel2',
            'ObsPath',
            'ObsAttribute',
            'DistinguishedName'
        )
        'group_edges.csv' = @(
            'ParentGroup',
            'ChildIdentity',
            'ChildObjectClass',
            'Depth',
            'IsCycle',
            'IsTruncated'
        )
        'permissioned_groups.csv' = @(
            'Group',
            'DisplayName',
            'ObjectClass',
            'ObsPath',
            'ManagerLevel1',
            'ShareAssignments',
            'NtfsAssignments',
            'ExpandedMembers',
            'MaxDepth',
            'HasCycle',
            'IsTruncated',
            'Rights',
            'ShareId',
            'ShareIds',
            'Sources',
            'FullPath',
            'ExamplePath'
        )
        'org_chains.csv' = @(
            'Identity',
            'EmployeeId',
            'EmployeeNumber',
            'Department',
            'Title',
            'Company',
            'ManagerLevel1',
            'ManagerLevel2',
            'ObsPath',
            'ObsAttribute'
        )
        'owner_mappings.csv' = @(
            'Pattern',
            'Owner',
            'BusinessUnit',
            'Source'
        )
        'owner_risk_pivots.csv' = @(
            'BusinessUnit',
            'Owner',
            'Pattern',
            'Source',
            'MatchingItems',
            'Directories',
            'Files',
            'FindingCount',
            'ConflictCount',
            'PartialShareCount',
            'DirectIdentityCount',
            'DirectGroupCount',
            'ExpandedMemberCount',
            'RiskLevel'
        )
        'related_data_areas.csv' = @(
            'RelatedAreaId',
            'RelatedDataArea',
            'BusinessUnit',
            'Owner',
            'Pattern',
            'Source',
            'RiskLevel',
            'MigrationReadiness',
            'MatchingShares',
            'MatchingItems',
            'Directories',
            'Files',
            'FindingCount',
            'ConflictCount',
            'ReviewItemCount',
            'PartialShareCount',
            'DirectIdentityCount',
            'DirectGroupCount',
            'ExpandedMemberCount',
            'RelatedBecause',
            'SuggestedNextAction'
        )
        'owner_review_packets.csv' = @(
            'ReviewPacketId',
            'BusinessUnit',
            'Owner',
            'Pattern',
            'Source',
            'RiskLevel',
            'ReviewStatus',
            'WhyReview',
            'WhatToReviewFirst',
            'SuggestedNextAction',
            'MatchingItems',
            'Directories',
            'Files',
            'FindingCount',
            'ConflictCount',
            'PartialShareCount',
            'DirectIdentityCount',
            'DirectGroupCount',
            'ExpandedMemberCount',
            'MigrationReadiness',
            'RelatedDataAreaCount'
        )
        'conflicts.csv' = @(
            'ConflictId',
            'ConflictType',
            'ShareId',
            'ItemId',
            'Identity',
            'ShareRights',
            'NtfsRights',
            'Severity',
            'Message'
        )
        'findings.csv' = @(
            'FindingId',
            'FindingType',
            'Severity',
            'ShareId',
            'ItemId',
            'FullPath',
            'Identity',
            'ObservedValue',
            'PolicyValue',
            'Message'
        )
        'collection_errors.csv' = @(
            'ErrorId',
            'ShareId',
            'ItemId',
            'FullPath',
            'ErrorType',
            'Severity',
            'Source',
            'Message',
            'Detail'
        )
        'scan_events.csv' = @(
            'EventId',
            'Timestamp',
            'Level',
            'EventType',
            'Source',
            'ShareId',
            'ItemId',
            'Message',
            'Detail'
        )
        'scan_manifest.csv' = @(
            'ScanId',
            'GeneratedAt',
            'ExportVersion',
            'ObsAttribute',
            'SourceMode',
            'OperationalPathLengthThreshold',
            'AzurePathComponentLimit',
            'AzureFullPathLimit',
            'ExplicitAceDepthThreshold',
            'GroupExpansionMaxDepth',
            'AdLookupMode',
            'IncludeFiles'
        )
    }
}
